'use strict';

export const ADD_TASK = 'ADD_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
export const EDIT_STATUS = 'EDIT_STATUS';
export const DEFAULT_STATUS = 'DEFAULT_STATUS';
export const GET_VIRTUAL_DATA_REQUEST = 'GET_VIRTUAL_DATA_REQUEST';
export const GET_VIRTUAL_DATA_SUCCESS = 'GET_VIRTUAL_DATA_SUCCESS';
export const GET_VIRTUAL_DATA_FAILED = 'GET_VIRTUAL_DATA_FAILED';